// DPC Hub · js/healthcheck.js · v1.0 · July 2026
// Health Check module. Upload ingestion (Forms Excel / Moodle format).
// AI extraction via Anthropic API (Haiku). DPC review and confirm/overwrite.
// Score writes to area Health Check record. Accessed from Areas or sidebar.

function initHealthChecks() {
  const main = document.getElementById('main-content');
  main.innerHTML = `
    <div id="banner-container" aria-live="polite"></div>
    <h1 style="font-size:var(--text-2xl);font-weight:var(--font-bold);color:var(--color-navy);margin-bottom:var(--space-sm);">Health Checks</h1>
    <p style="font-size:var(--text-base);color:var(--color-muted);margin-bottom:var(--space-xl);">Upload a Digital Health Check export to extract scores and generate a provisional RAG assessment for your review.</p>

    <!-- Area selector -->
    <div style="display:grid;grid-template-columns:300px 1fr;gap:var(--space-xl);align-items:start;">
      <div>
        <div class="form-group">
          <label class="form-label" for="hc-area-sel">Select area</label>
          <select class="form-select" id="hc-area-sel" aria-label="Select area for Health Check">
            <option value="">— Select area —</option>
          </select>
        </div>
        <div id="hc-area-history"></div>
      </div>

      <div id="hc-main-panel">
        <div id="hc-upload-section" style="display:none;">
          <h2 style="font-size:var(--text-lg);font-weight:var(--font-bold);color:var(--color-navy);margin-bottom:var(--space-md);">Upload Health Check</h2>

          <!-- Upload zone -->
          <div id="hc-drop-zone" style="
            border:2px dashed var(--color-teal);border-radius:var(--radius-md);
            padding:var(--space-2xl);text-align:center;
            background:var(--color-teal-lt);cursor:pointer;
            transition:background 150ms ease;margin-bottom:var(--space-lg);"
            role="button" tabindex="0" aria-label="Upload Health Check file — click or drag and drop">
            <p style="font-size:var(--text-lg);color:var(--color-teal);margin-bottom:var(--space-sm);">📋</p>
            <p style="font-size:var(--text-base);font-weight:var(--font-bold);color:var(--color-teal);">Drop file here or click to upload</p>
            <p style="font-size:var(--text-sm);color:var(--color-muted);margin-top:var(--space-xs);">Accepts .xlsx, .csv, or .txt exports from Forms or Moodle</p>
            <input type="file" id="hc-file-input" accept=".xlsx,.csv,.txt,.xls" style="display:none;" aria-label="Upload Health Check file">
          </div>

          <!-- Manual text entry (fallback) -->
          <details style="margin-bottom:var(--space-lg);">
            <summary style="cursor:pointer;font-size:var(--text-sm);color:var(--color-muted);padding:var(--space-sm) 0;">Or paste Health Check responses as text</summary>
            <textarea id="hc-text-input" class="form-textarea" rows="8" style="margin-top:var(--space-sm);" placeholder="Paste the Health Check responses here — e.g. copied from a Forms summary, email, or document…"></textarea>
            <button id="hc-text-extract-btn" type="button" class="btn btn--ghost btn--sm" style="margin-top:var(--space-sm);">Extract from text →</button>
          </details>

          <div id="hc-processing" style="display:none;text-align:center;padding:var(--space-xl);">
            <div class="loading-spinner" style="width:32px;height:32px;border-color:rgba(15,118,110,0.2);border-top-color:var(--color-teal);margin:0 auto var(--space-md);"></div>
            <p style="font-size:var(--text-base);color:var(--color-teal);">Reading file and mapping to framework…</p>
          </div>
        </div>

        <!-- Review section -->
        <div id="hc-review-section" style="display:none;">
          <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--space-lg);">
            <h2 style="font-size:var(--text-lg);font-weight:var(--font-bold);color:var(--color-navy);">Review extracted scores</h2>
            <button id="hc-reset-btn" type="button" class="btn btn--ghost btn--sm">← Upload new file</button>
          </div>
          <div style="background:var(--color-amber-lt);border:1px solid var(--color-amber);border-radius:var(--radius-sm);padding:var(--space-md);margin-bottom:var(--space-lg);font-size:var(--text-sm);color:var(--color-amber);">
            These scores were generated by AI from the uploaded file. Review each one — your professional judgement is always the final word. Confirm or override before saving.
          </div>
          <div id="hc-dimension-rows"></div>
          <div class="form-group" style="margin-top:var(--space-lg);">
            <label class="form-label form-label--optional" for="hc-context-note">DPC context note</label>
            <textarea class="form-textarea" id="hc-context-note" rows="2" placeholder="Any context you want to add to the record — e.g. known changes since the check was completed…"></textarea>
          </div>
          <div class="btn-row">
            <button id="hc-save-all" type="button" class="btn btn--primary">Confirm all scores</button>
          </div>
        </div>

        <!-- Placeholder when no area selected -->
        <div id="hc-placeholder" style="padding:var(--space-2xl);text-align:center;color:var(--color-muted);">
          <p style="font-size:48px;margin-bottom:var(--space-md);">📊</p>
          <p style="font-size:var(--text-base);">Select an area to upload or review its Health Check.</p>
        </div>
      </div>
    </div>
  `;

  _hcPopulateAreaSelector();
  _wireHCEvents();
}

// ── Health Check dimensions ───────────────────────────────────
const HC_DIMENSIONS = [
  { id:'digitalLearningEnv',    label:'Digital Learning Environment',    desc:'Teams channel structure, resource organisation, navigation.' },
  { id:'inclusivePractice',     label:'Inclusive Practice',              desc:'UDL, personalisation, SEND support, language and literacy.' },
  { id:'accessibilityByDesign', label:'Accessibility by Design',         desc:'WCAG compliance, alt text, contrast, accessible resources.' },
  { id:'staffCapabilityHC',     label:'Staff Digital Capability',        desc:'Staff confidence and use of digital tools for learning.' },
  { id:'learnerDigitalSkills',  label:'Learner Digital Skills',          desc:'Learner ability to use digital tools independently.' },
];

// ── Area selector ─────────────────────────────────────────────
function _hcPopulateAreaSelector() {
  const sel = document.getElementById('hc-area-sel');
  if (!sel) return;
  (_getAreas()||[]).sort((a,b)=>a.areaName.localeCompare(b.areaName)).forEach(area=>{
    const opt=document.createElement('option');
    opt.value=area.areaCode; opt.textContent=`${area.areaCode} — ${area.areaName}`; sel.appendChild(opt);
  });
}

function _hcShowAreaHistory(areaCode) {
  const container = document.getElementById('hc-area-history');
  if (!container) return;
  const area = _getArea(areaCode);
  const checks = (area&&area.healthChecks)||[];
  if (checks.length===0) { container.innerHTML='<p style="font-size:var(--text-xs);color:var(--color-muted);margin-top:var(--space-md);">No Health Checks recorded yet.</p>'; return; }
  const sorted = checks.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));
  container.innerHTML=`
    <h3 style="font-size:var(--text-sm);font-weight:var(--font-bold);color:var(--color-navy);margin-top:var(--space-lg);margin-bottom:var(--space-sm);">Previous checks</h3>
    ${sorted.map(hc=>`
      <div style="padding:var(--space-sm);border:1px solid var(--color-border);border-radius:var(--radius-sm);margin-bottom:var(--space-xs);">
        <p style="font-size:var(--text-xs);font-weight:bold;color:var(--color-slate);">${_hcFmtDate(hc.date)}</p>
        <div style="display:flex;gap:4px;flex-wrap:wrap;margin-top:4px;">
          ${HC_DIMENSIONS.map(d=>{
            const score=hc.scores&&hc.scores[d.id];
            const col=score?['','var(--color-red)','var(--color-amber)','var(--color-amber)','var(--color-green)','var(--color-green)'][score]:'var(--color-border)';
            return `<span style="font-size:10px;background:${col};color:#fff;padding:1px 6px;border-radius:999px;font-weight:bold;" title="${d.label}">${score||'?'}</span>`;
          }).join('')}
        </div>
      </div>`).join('')}
  `;
}

// ── Wire events ───────────────────────────────────────────────
function _wireHCEvents() {
  document.getElementById('hc-area-sel')?.addEventListener('change', e=>{
    const areaCode = e.target.value;
    const upload   = document.getElementById('hc-upload-section');
    const placeholder=document.getElementById('hc-placeholder');
    const review   = document.getElementById('hc-review-section');
    if (!areaCode) {
      if(upload) upload.style.display='none';
      if(placeholder) placeholder.style.display='block';
      return;
    }
    if(placeholder) placeholder.style.display='none';
    if(review) review.style.display='none';
    if(upload) upload.style.display='block';
    _hcShowAreaHistory(areaCode);
  });

  // File drop zone
  const dropZone = document.getElementById('hc-drop-zone');
  const fileInput = document.getElementById('hc-file-input');

  dropZone?.addEventListener('click', ()=>fileInput?.click());
  dropZone?.addEventListener('keydown', e=>{ if(e.key==='Enter'||e.key===' ') fileInput?.click(); });
  dropZone?.addEventListener('dragover', e=>{ e.preventDefault(); dropZone.style.background='#C7E9E5'; });
  dropZone?.addEventListener('dragleave', ()=>{ dropZone.style.background='var(--color-teal-lt)'; });
  dropZone?.addEventListener('drop', e=>{ e.preventDefault(); dropZone.style.background='var(--color-teal-lt)'; const f=e.dataTransfer?.files[0]; if(f) _processHCFile(f); });
  fileInput?.addEventListener('change', e=>{ const f=e.target.files[0]; if(f) _processHCFile(f); });

  // Text extraction
  document.getElementById('hc-text-extract-btn')?.addEventListener('click', ()=>{
    const text = document.getElementById('hc-text-input')?.value.trim();
    if (!text) return;
    _extractFromText(text);
  });

  // Reset
  document.getElementById('hc-reset-btn')?.addEventListener('click', ()=>{
    document.getElementById('hc-review-section').style.display='none';
    document.getElementById('hc-upload-section').style.display='block';
    if(document.getElementById('hc-file-input')) document.getElementById('hc-file-input').value='';
  });

  // Save all
  document.getElementById('hc-save-all')?.addEventListener('click', _saveHCScores);
}

// ── File processing ───────────────────────────────────────────
async function _processHCFile(file) {
  const processing = document.getElementById('hc-processing');
  const upload     = document.getElementById('hc-upload-section');
  if(processing) processing.style.display='block';
  if(upload) upload.querySelector('#hc-drop-zone').style.opacity='0.5';

  try {
    // Read file as text (works for CSV and txt; xlsx will be binary)
    const text = await _readFileAsText(file);
    await _extractFromText(text, file.name);
  } catch(err) {
    if(processing) processing.style.display='none';
    if(typeof UI!=='undefined') UI.showToast('error', `Could not read file: ${err.message}`);
  }
}

function _readFileAsText(file) {
  return new Promise((resolve, reject)=>{
    const reader = new FileReader();
    reader.onload  = e => resolve(e.target.result);
    reader.onerror = () => reject(new Error('File read failed'));
    reader.readAsText(file);
  });
}

async function _extractFromText(text, filename='') {
  const processing = document.getElementById('hc-processing');
  if(processing) processing.style.display='block';

  try {
    // Call Anthropic Haiku to map responses to framework dimensions
    const prompt = `You are analysing a Digital Health Check from an FE college. Extract scores for each dimension.

The five dimensions are:
1. Digital Learning Environment — Teams channel structure, resource organisation, navigation, accessibility of digital spaces
2. Inclusive Practice — UDL, personalisation, SEND support, language and literacy embedding
3. Accessibility by Design — WCAG compliance, alt text, colour contrast, accessible resource creation
4. Staff Digital Capability — Staff confidence and effective use of digital tools for teaching, learning and assessment
5. Learner Digital Skills — Learner ability to navigate and use digital tools independently

Score each dimension 1–5 where:
1 = Immediate concern / not present
2 = Significant development needed
3 = Developing / partially in place
4 = Establishing / mostly in place
5 = Embedded / consistently strong

Analyse this Health Check data:
---
${text.substring(0, 3000)}
---

Respond ONLY with valid JSON in this exact format, no other text:
{
  "digitalLearningEnv": { "score": 3, "rationale": "brief explanation" },
  "inclusivePractice": { "score": 3, "rationale": "brief explanation" },
  "accessibilityByDesign": { "score": 2, "rationale": "brief explanation" },
  "staffCapabilityHC": { "score": 3, "rationale": "brief explanation" },
  "learnerDigitalSkills": { "score": 3, "rationale": "brief explanation" }
}`;

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1000,
        messages: [{ role: 'user', content: prompt }]
      })
    });

    if (!response.ok) throw new Error(`API error: ${response.status}`);
    const data = await response.json();
    const raw  = data.content?.[0]?.text || '';

    // Parse JSON response
    const clean = raw.replace(/```json|```/g,'').trim();
    const scores = JSON.parse(clean);

    if(processing) processing.style.display='none';
    _renderHCReview(scores, filename);

  } catch(err) {
    if(processing) processing.style.display='none';
    // Fallback: show manual entry form if API fails
    console.warn('DPC Hub: HC extraction failed, showing manual entry:', err);
    _renderHCManualReview(filename);
  }
}

// ── Render review panel ───────────────────────────────────────
function _renderHCReview(scores, source='') {
  const upload = document.getElementById('hc-upload-section');
  const review = document.getElementById('hc-review-section');
  const rows   = document.getElementById('hc-dimension-rows');
  if(upload) upload.style.display='none';
  if(review) review.style.display='block';
  if(!rows) return;

  rows.innerHTML = HC_DIMENSIONS.map(dim=>{
    const extracted = scores[dim.id] || { score: null, rationale: '' };
    const score     = extracted.score;
    return `
      <div style="border:1px solid var(--color-border);border-radius:var(--radius-md);padding:var(--space-lg);margin-bottom:var(--space-md);">
        <div style="display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:var(--space-md);flex-wrap:wrap;gap:var(--space-sm);">
          <div>
            <h3 style="font-size:var(--text-base);font-weight:var(--font-bold);color:var(--color-navy);">${dim.label}</h3>
            <p style="font-size:var(--text-xs);color:var(--color-muted);">${dim.desc}</p>
          </div>
          <div style="display:flex;gap:var(--space-xs);" role="group" aria-label="Score for ${dim.label}">
            ${[1,2,3,4,5].map(s=>{
              const sel = s===score;
              const bg  = sel ? _ragColour(s) : 'var(--color-white)';
              const col = sel ? 'var(--color-white)' : 'var(--color-muted)';
              return `<label style="cursor:pointer;">
                <input type="radio" name="hc-score-${dim.id}" value="${s}" ${sel?'checked':''} style="position:absolute;opacity:0;width:0;height:0;" aria-label="Score ${s}">
                <span class="hc-score-btn" data-dim="${dim.id}" data-score="${s}" style="
                  display:inline-flex;align-items:center;justify-content:center;
                  width:44px;height:44px;border-radius:var(--radius-sm);
                  border:2px solid ${sel?_ragColour(s):'var(--color-border)'};
                  background:${bg};color:${col};
                  font-weight:var(--font-bold);font-size:var(--text-base);
                  cursor:pointer;transition:all 150ms;user-select:none;"
                  aria-hidden="true">${s}</span>
              </label>`;
            }).join('')}
          </div>
        </div>
        ${extracted.rationale?`
          <div style="background:var(--color-teal-lt);border-radius:var(--radius-sm);padding:var(--space-sm);margin-bottom:var(--space-sm);">
            <p style="font-size:var(--text-xs);color:var(--color-teal);font-weight:bold;margin-bottom:2px;">AI rationale:</p>
            <p style="font-size:var(--text-sm);color:var(--color-slate);">${_hcEsc(extracted.rationale)}</p>
          </div>`:''}
        <label style="display:block;font-size:var(--text-xs);color:var(--color-muted);margin-bottom:4px;" for="hc-rationale-${dim.id}">Your rationale / override note</label>
        <textarea id="hc-rationale-${dim.id}" rows="2" style="width:100%;padding:var(--space-xs) var(--space-sm);border:1px solid var(--color-border);border-radius:var(--radius-sm);font:var(--text-sm) Arial,sans-serif;resize:vertical;">${_hcEsc(extracted.rationale||'')}</textarea>
      </div>`;
  }).join('');

  // Wire score button visual feedback
  rows.addEventListener('click', e=>{
    const btn = e.target.closest('.hc-score-btn');
    if (!btn) return;
    const dimId = btn.dataset.dim;
    const score = parseInt(btn.dataset.score);
    document.querySelectorAll(`.hc-score-btn[data-dim="${dimId}"]`).forEach(b=>{
      const s   = parseInt(b.dataset.score);
      const sel = s===score;
      b.style.background   = sel ? _ragColour(s) : 'var(--color-white)';
      b.style.color        = sel ? 'var(--color-white)' : 'var(--color-muted)';
      b.style.borderColor  = sel ? _ragColour(s) : 'var(--color-border)';
    });
    const radio = document.querySelector(`input[name="hc-score-${dimId}"][value="${score}"]`);
    if(radio) radio.checked=true;
  });
}

function _renderHCManualReview(source='') {
  // No AI extraction — show all dimensions with blank scores for manual entry
  const blankScores = {};
  HC_DIMENSIONS.forEach(d=>{ blankScores[d.id]={score:null,rationale:''}; });
  _renderHCReview(blankScores, source);
}

// ── Save confirmed scores ─────────────────────────────────────
function _saveHCScores() {
  const areaCode = document.getElementById('hc-area-sel')?.value;
  if (!areaCode) return;

  const area = _getArea(areaCode);
  if (!area) return;

  const scores = {};
  HC_DIMENSIONS.forEach(dim=>{
    const radio = document.querySelector(`input[name="hc-score-${dim.id}"]:checked`);
    const rationale = document.getElementById(`hc-rationale-${dim.id}`)?.value.trim()||'';
    if (radio) {
      scores[dim.id] = { score: parseInt(radio.value), rationale, confirmedAt: nowISO() };
    }
  });

  const hcRecord = {
    hcId:        generateId(),
    date:        todayISO(),
    scores,
    contextNote: document.getElementById('hc-context-note')?.value.trim()||'',
    confirmedBy: 'DPC',
    confirmedAt: nowISO(),
  };

  if (!area.healthChecks) area.healthChecks=[];
  area.healthChecks.push(hcRecord);
  area.lastUpdated = nowISO();
  saveArea(area);

  // Update accessibility dimension on area RAG
  if (scores.accessibilityByDesign) {
    if (!area.ragDimensions) area.ragDimensions={};
    if (!area.ragDimensions.accessibilityInclusion) {
      area.ragDimensions.accessibilityInclusion={
        score: scores.accessibilityByDesign.score,
        rationale: `From Health Check ${todayISO()}: ${scores.accessibilityByDesign.rationale}`,
        updatedAt: nowISO()
      };
      saveArea(area);
    }
  }

  if (typeof UI!=='undefined') UI.showToast('success', `Health Check saved for ${areaCode}. ${Object.keys(scores).length} dimensions confirmed.`);
  _hcShowAreaHistory(areaCode);
  document.getElementById('hc-review-section').style.display='none';
  document.getElementById('hc-upload-section').style.display='block';
}

function _ragColour(score) {
  return ['','#DC2626','#B45309','#B45309','#15803D','#15803D'][score]||'#64748B';
}
function _hcFmtDate(iso){if(!iso)return'';try{return new Date(iso.split('T')[0]+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}catch{return iso;}}
function _hcEsc(str){if(!str)return'';return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
